### ISSUE TITLE
Wikis allow git pushes with illegal filenames

### ISSUE THREAD

**Issue by supernova32** [gollum/gollum-lib#103]
moved from: https://github.com/gollum/gollum/issues/881

I've been using GitLab, and it uses Gollum for the wikis. Gollum is quite picky about the slugs (URLs) of its pages. The slugs get generated automatically from filenames in its underlying Git repository. Right now a user can do the following:

create a wiki;
download the wiki via Git;
create a file 'a&b.markdown';
git push;
go to the wiki pages index for the project.
The result will be a 500 due to a 'routing error', which seems to be the fault of the '&'.

This seems to be an issue with Gollum and not GitLab, because Gollum is allowing the creation of a file with an illegal filename.

**Comment by dometto** [comment]
This is fixed in `5.x`

**Comment by ulidtko** [comment]
Hey, where's the place to tweak this behavior? Will I need to fork/patch `gollum-lib` to change it?..

I'm putting `gollum` in place of a `dokuwiki` integrated inside yet another, python web app (yeah... `gollum` saves me from having to deal with PHP). Basically, that app allows pinning wiki notes to UI objects which happen to be **IP addresses** with rich info around them.

So, it does work, but instead of nice tidy `127.0.0.1.md` I'm getting `127-dot-0-dot-0-1.md` which is kinda ugly, let's admit that. (And yes, for some reason the third `dot` is not there.)

My experience with Ruby so far is on the order of 2-3 kLoC-ish, so I'd honestly appreciate any pointers here.

**Comment by ulidtko** [comment]
Oh well, never mind. The pages are easy to rename back to what I want.

**Comment by bartkamphorst** [comment]
@ulidtko Have you tried the `5.x` branch? The "page name rewrite magic" has been removed there.

**Comment by ulidtko** [comment]
@bartkamphorst nice, thanks for the tip!

I gave it a try, but unfortunately, the 5.x gem doesn't build... As far as I can see, the spec file hasn't been updated to keep up with other 5.x changes (lists many files which have been removed). I'll file a separate issue for that.
