### ISSUE TITLE
Security Contact

### ISSUE THREAD

**Issue by joernchen** [gollum/gollum-lib#120]
Hi, 

this is kind of a "meta" issue, but I was wondering where I can
disclose a security issue in gollum? Due to the severity of the issue
I don't want to just put it in this public issue tracker.

thx,

joernchen

**Comment by SkyCrawl** [comment]
@dometto 

I was curious so I had a look around but couldn't really find a nice option to create a free, closed and trustworthy mailing list. Do you know of any?

If not, a quick alternative might be a special Google Group (GG) and a GPG key? Simply put, by registering a GG, you get a global email address that redirects all traffic (within the group or from outside) to the members (except for the sender). Now, if the traffic was to be encrypted by a GPG key for the group address, Google itself will only see the encrypted message, both at the group and potentially at member addresses. Members can then use email clients to locally decipher the messages.

Not perfect but I think it's definitely an option. There are several problems that I can see atm:
* The use of a GPG-enabled email client is a must, since we want the messages to be decrypted only on machines owned by the members.
* Distribution of the private key and its associated passphrase, changing which is not a very comfortable process (the key would probably have to be redestributed again, and history potentially lost over time).
* To avoid spam messages, emails to the group should probably have a specific subject format.
* All member communication should be encrypted again, with the GG's public key.
* With this setup, it's impossible for multiple members to have an encrypted conversation with the issue-reporter so only a single person should probably handle that.

All in all, it seems a very viable option, with 1 or 2 members. It is probably also a better alternative to having your personal address used for this purpose since you most probably will not be handing over access to it anytime in the future :).

**Comment by dometto** [comment]
There is actually a gollum-dev group already (although not used). I think as an alternative to a shared private key, which I take it you are suggesting and which just opens up the question of how to safely share the key and ensure it is passed on to future developers, it would be fine to have a personal key fingerprint for as many people in the group in the readme.

**Comment by SkyCrawl** [comment]
With a little effort, the distribution can be done quite safely, as long as the members treat the key with care. To ensure it is passed on would probably mean at least 2 members in the group. And if, for some reason, that fails, creating a new group and key is always a possibility, however inconvenient :).

But you're right that your suggestion is also an alternative. To me, they are more or less equal since they both have advantages and disadvantages. Yet, it's maybe wiser not to over-kill this indeed :).
