### ISSUE TITLE
Error when trying to build from source

### ISSUE THREAD

**Issue by techwiz24** [gollum/gollum-lib#152]
When trying to run `rake build`, I get this error:

```
Directory `lib` should only contain a `gollum-lib_java.rb` file and `gollum-lib_java` dir.
```

**Comment by bartkamphorst** [comment]
Interesting error. Will try to investigate this weekend.

**Comment by dometto** [comment]
Strange, I can't reproduce this. Still, I think [this line](https://github.com/gollum/gollum-lib/blob/master/Rakefile#L12) is the culprit:
```ruby
Dir['*.gemspec'].first.split('.').first
```
Possibly that returns `gollum-lib` on my machine and `gollum-lib_java` on yours, due to different sorting of `Dir[]` on ubuntu/OS X?

Can you try changing `Dir['*.gemspec'].first.split('.').first` to just read `"gollum-lib"`? If that works I'll change it on `master`. In this case I'm all for hardcoding the name. :)

**Comment by techwiz24** [comment]
Seems to be the case. By hard-coding the name to `"gollum-lib"` it will now build. Also, your hunch about sorting seems to be right:

```bash
gollum@wikitest:~/gollum-lib$ irb
irb(main):001:0> Dir['*.gemspec']
=> ["gollum-lib_java.gemspec", "gollum-lib.gemspec"]
```

**Comment by bartkamphorst** [comment]
Should the `name` helper in the `Rakefile` check `RUBY_PLATFORM`?

**Comment by dometto** [comment]
Glad you got it working!

@bartkamphorst, I think that would be too much effort for what that method is trying to accomplish. Hardcoding or setting a constant seem fine to me.

**Comment by techwiz24** [comment]
@dometto @bartkamphorst, I know it's simple, but did you guys want a PR for this?

**Comment by dometto** [comment]
Thanks, pushed the fix just now :)
