### ISSUE TITLE
AsciiDoc includes don't work in ---- code blocks

### ISSUE THREAD

**Issue by mchill** [gollum/gollum-lib#169]
As an example, this won't render correctly:

```
----
include::other-file.asciidoc[]
----
```

The problem is that Gollum [parses AsciiDoc code blocks](https://github.com/gollum/gollum-lib/blob/84275c3f5c2e400deb5181861cd2ac9e72f24d1d/lib/gollum-lib/filter/code.rb#L13) before rendering with Asciidoctor. This is done so that Gollum can apply syntax highlighting to the code blocks, but Asciidoctor can handle that itself.

The solution that I have found involves removing the line I linked to and overloading github-markup's [AsciiDoc markup](https://github.com/github/markup/blob/master/lib/github/markups.rb#L32) function to use pygments syntax highlighting. (I also use the :safe => :safe option to make include work at all, but that's a security vulnerability that needs to be looked at more carefully.) Then I change template.css to accept Asciidoctor's custom pygments class names (it prefixes each class with 'tok-').

Any opinions on how to implement a better fix? I can submit a PR if this seems like a reasonable solution.

**Comment by bartkamphorst** [comment]
> I also use the :safe => :safe option to make include work at all

@mchill Do you enable this in `config.rb`? If so, how?

**Comment by dometto** [comment]
On `5.x` we can now skip the code filter entirely for `asciidoc` by using the `:skip_filters` key when registering `asciidoc` with `Gollum::Markup.register`. Do we want to leave all syntax highlighting to `asciidoctor` by default? I believe we would still have to override some of `github-markup`'s settings to achieve that, but shouldn't the CSS already work out of the box? I thought we also use `pygments` when it is present.

**Comment by dometto** [comment]
We will not support `asciidoc` includes in codeblocks because we don't want to outsource responsibility for the generated syntax highlighting CSS to all the different markup renderers, for the sake of maintainability and uniformity. Anyone who wants to disable gollum's own syntax highlighting feature for `asciidoc` or any other format can do so using the `skip_filters`   key ([see here](https://github.com/gollum/gollum/wiki/Customizing-rendering-settings)).
