### ISSUE TITLE
AsciiDoc link/include paths are relative from repo root

### ISSUE THREAD

**Issue by mchill** [gollum/gollum-lib#170]
Because all pages are rendered from the root of the git repository Gollum is serving from, AsciiDoc relative link and include paths don't function as they should.

An easy fix is to wrap [this line](https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/filter/render.rb#L6) in a chdir block like this:

``` ruby
Dir.chdir(@markup.dir) do
  data = GitHub::Markup.render(@markup.name, data)
end
```

I'm not sure if that would break any other markup language's rendering, though. Thoughts on whether this should be implemented for all languages, just AsciiDoc, or not at all?

**Comment by dometto** [comment]
Sorry for the late reply. I actually think this should be a relatively safe fix, since gollum's own tags shouldn't (and I think don't) care about what the working directory is. Would you like to try a PR (against the `gollum-lib-5.x` branch) for this? If the tests pass with this line around it I'm ok with merging it in. Perhaps it will also have a beneficial effect on other markups with similar functionality (org?).

**Comment by dometto** [comment]
Implemented in 5.x
