### ISSUE TITLE
Escaped emoji

### ISSUE THREAD

**Issue by svoop** [gollum/gollum-lib#273]
Every now and then, wanna-be emoji tags are replaced with their corresponding emoji image: For instance `rake app:shell:open` will become "rake app:shell:open". (It doesn't here on Github, but will on Gollum since context-agnostic filters are used to handle emoji. Which is good, because unlike Github it allows emoji e.g. in code blocks which is useful at times.)

I've written a very small fix for this problem by adding the ability to escape emoji by prefixing the first colon with a backslash: `app\:shell:open` reners as `app:shell:open`

@dometto I'm not sure whether to create a PR on master or the v5 branch or both. What do you think?

**Comment by dometto** [comment]
Please open one against `5.x`! Are we sure rendering emojis in code blocks is desired behavior though? (The impact is low because emojis are not turned on by default, but still.) Another way of handling this problem might be to change the location of the `Emoji` filter in the filter chain though (but I haven't looked into this).

**Comment by svoop** [comment]
Me, personally, I like it to be able to highlight stuff in code blocks with emoji – particularly since all other formatting is of course impossible. Graphics stand out way more and nobody confuses them with the actual code. So as far as I'm concerned, it's a feature, not a bug.

**Comment by svoop** [comment]
Here you go:

* https://github.com/gollum/gollum-lib/pull/275
* https://github.com/gollum/gollum/pull/1235

**Comment by dometto** [comment]
Fixed in those PRs.
